all:
	scalac -cp ../../akka-2.0.5/lib/akka/akka-actor-2.0.5.jar:../../akka-2.0.5/lib/akka/config-0.3.1.jar test.scala
export:
	export AKKA_HOME=/home/scony/Programming/Scala/akka-2.0.5
run:
	java -cp ../../akka-2.0.5/lib/scala-library.jar:../../akka-2.0.5/lib/akka/akka-actor-2.0.5.jar:../../akka-2.0.5/lib/akka/config-0.3.1.jar:. com.sconysoft.test.multilevel.Mlvl
